---
version: '3'

services:

  postgres:
    build:
      context: './postgres'
    environment:
      POSTGRES_USER: 'atmo_app'
      POSTGRES_PASSWORD: 'atmosphere'
      POSTGRES_DB: 'atmo_prod'
      TROPO_DB_NAME: 'troposphere'

  atmosphere:
    image: 'cyverse/atmosphere:latest'
    volumes:
      - '../atmosphere:/opt/dev/atmosphere'
      - '../atmosphere-ansible:/opt/dev/atmosphere-ansible'
      - '../atmosphere-docker-secrets:/opt/dev/atmosphere-docker-secrets'
    depends_on:
      - 'postgres'

  troposphere:
    image: 'cyverse/troposphere:latest'
    volumes:
      - '../troposphere:/opt/dev/troposphere'
      - '../atmosphere-docker-secrets:/opt/dev/atmosphere-docker-secrets'
    depends_on:
      - 'atmosphere'
    ports:
      - '443:443'
      - '80:80'
