---
version: '3'

services:

  postgres:
    build:
      context: './postgres'
    environment:
      POSTGRES_USER: 'atmo_app'
      POSTGRES_PASSWORD: 'atmosphere'
      POSTGRES_DB: 'atmo_prod'
      TROPO_DB_NAME: 'troposphere'

  atmosphere:
    image: 'cyverse/atmosphere:latest'
    depends_on:
      - 'postgres'

  troposphere:
    image: 'cyverse/troposphere:latest'
    depends_on:
      - 'atmosphere'
    ports:
      - '443:443'
      - '80:80'

  tester:
    build:
      context: './tester'
    entrypoint: 'sleep 300 && /test.sh'
    depends_on:
      - 'atmosphere'
      - 'troposphere'
