---
version: '3'

services:

  redis:
    image: 'redis:latest'

  postgres:
    image: 'postgres:9.6'
    volumes:
      - './postgres:/docker-entrypoint-initdb.d'
    environment:
      POSTGRES_USER: 'atmo_app'
      POSTGRES_PASSWORD: 'atmosphere'
      POSTGRES_DB: 'atmo_prod'
      TROPO_DB_NAME: 'troposphere'
    ports:
      - '5432:5432'
    network_mode: 'host'

  celery:
    build: './celery'
    command: '' # put your user id here if running locally
    environment:
      env_type: "dev"
    volumes:
      - '../atmosphere:/opt/dev/atmosphere'
      - '../atmosphere-ansible:/opt/dev/atmosphere-ansible'
    depends_on:
      - 'redis'
    extra_hosts:
      - 'postgres:${dockerhost}'

  atmosphere:
    image: 'cyverse/atmosphere:latest'
    command: '' # put your user id here if running locally
    volumes:
      - '../atmosphere:/opt/dev/atmosphere'
      - '../atmosphere-ansible:/opt/dev/atmosphere-ansible'
      - '../atmosphere-docker-secrets:/opt/dev/atmosphere-docker-secrets'
      - '/boot:/boot'
      - '/lib/modules:/lib/modules'
    depends_on:
      - 'postgres'
      - 'celery'
    extra_hosts:
      - 'postgres:${dockerhost}'

  troposphere:
    image: 'cyverse/troposphere:latest'
    command: '' # put your user id here if running locally
    volumes:
      - '../troposphere:/opt/dev/troposphere'
      - '../atmosphere-docker-secrets:/opt/dev/atmosphere-docker-secrets'
    depends_on:
      - 'atmosphere'
    ports:
      - '443:443'
      - '80:80'
    extra_hosts:
      - 'postgres:${dockerhost}'
